<?php

namespace FormationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends EntityRepository
{
    // public function findTeacher
}
